version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use variável de ambiente para a senha
      POSTGRES_USER: ${POSTGRES_USER}         # Use variável de ambiente para o usuário
      POSTGRES_DB: ${POSTGRES_DB}             # Nome do banco de dados PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data # Persistir dados do PostgreSQL
    networks:
      - backend-network

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} # Use variável de ambiente para o usuário
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} # Use variável de ambiente para a senha
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db # Persistir dados do MongoDB
    networks:
      - backend-network

  metabase:
    image: metabase/metabase
    restart: always
    depends_on:
      - db
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}          # Nome do banco de dados para o Metabase
      MB_DB_PORT: "5432"
      MB_DB_USER: ${POSTGRES_USER}          # Usuário do banco de dados para o Metabase
      MB_DB_PASS: ${POSTGRES_PASSWORD}      # Senha do banco de dados para o Metabase
      MB_DB_HOST: localhost
    ports:
      - "3000:3000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  mongo-data:
    driver: local
  metabase-data:
    driver: local
